### ISSUE TITLE
Add Glviewer Mouse Control

### ISSUE THREAD

**Issue by grantbrown** [grantbrown/laspy#2]
Currently uses keyboard based navigation.

**Comment by silyko** [comment]
Have just added a PyQt4 based viewer (with minor modifications of your original code) in my fork. Could be useful?
PyQt4 makes some things, like mouse integration, buttons etc., quite easy...

**Comment by grantbrown** [comment]
I'd actually been considering removing the viewer from laspy and instead making it a separate project. That would keep laspy focused on it's core job of handling las data, and help keep the codebase manageable. A Qt4 based viewer would be nice in that context. 

I wonder if [Howard](https://github.com/hobu) has any thoughts on this.

**Comment by hobu** [comment]
> I wonder if Howard has any thoughts on this.

Not in particular, but if you think it would draw more contribution, it might be good to separate it.

**Comment by grantbrown** [comment]
Any interest in taking point on a laspy based 3d viewer Simon?

**Comment by silyko** [comment]
I think it makes sense to make a separate project - at least if it's going to be a "larger" viewer with more GUI stuff. Wouldn't mind starting a project based on the laspy code.

I think it would make sense, at some point, also to make things a bit more abstract so that it becomes a more general "pointcloud viewer". Of course with LAS/LAZ files provided by laspy  as the primary source. But would be nice to also be able to read simple text files, npy /npz files and perhaps web based things. I suppose that the infrastructure in laspy is almost already in place for that. Could also just be something as simple as providing objects with at least x, y and z attributes and possible some of the other attributes (intensity, rgb,...) that LIDAR data has. 
But let's start out with the primary thing: a laspy based pointcloud viewer :-)

**Comment by silyko** [comment]
Of course there is already something like CloudCompare, which is quite advanced. No need to implement all that.
But was just amazed at how much faster, and simpler, the OpenGL code in laspy is. And I guess it's good to keep it simple!

**Comment by silyko** [comment]
Have started a small repo here: https://github.com/silyko/lasviewer

**Comment by grantbrown** [comment]
Cool, I'll close this issue and open one targeted at updating our documentation and removing the GL stuff. I think we should wait to yank it out until corresponding documentation/distribution for lasviewer is in place.
