### ISSUE TITLE
laspy for Python 3

### ISSUE THREAD

**Issue by earthflat** [grantbrown/laspy#40]
Hi, 

I've tried to install the new laspy 1.4.0 in a Python 3.4 environment. It does not work. With laspy 1.2.5 it used to work. I know that laspy focuses on Python 2.7 but since i need to work with Pythonb 3 I would like to know if is there is a way to install it?

Here is the error message for pip install laspy for Python 3.4.3:

(rs)mac:~ will$ pip install laspy
Collecting laspy
  Using cached laspy-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/gz/t3r4_mbs2g11gd54w4ksj7xc0020_6/T/pip-build-72bnfzq8/laspy/setup.py", line 4, in <module>
        import laspy
      File "/private/var/folders/gz/t3r4_mbs2g11gd54w4ksj7xc0020_6/T/pip-build-72bnfzq8/laspy/laspy/__init__.py", line 3, in <module>
        import base
    ImportError: No module named 'base'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gz/t3r4_mbs2g11gd54w4ksj7xc0020_6/T/pip-build-72bnfzq8/laspy

**Comment by grantbrown** [comment]
The older versions of laspy are still available on [PyPi](https://pypi.python.org/pypi/laspy/1.2.5), and of course every change is saved on GitHub. You can install a specific version by [using Pip](http://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip).

With that being said, I would expect performance issues and bugs when using 1.2.5 with Python 3. 

Unfortunately, I don't have the time to overhaul laspy for Python 3 compatibility, but will consider pull requests which implement it (so long as they don't break 2.7). It looks like [GeospatialPython](https://github.com/GeospatialPython/laspy) has made some progress on this front, though they've also made other changes I'm not sure we want to merge.

**Comment by umbe1987** [comment]
Hi,

I am kind of a fan of laspy since I recently discovered it and tried it with a few LAS files I have.
I now am in trouble because I am forced to use a python installation shipped with a GIS software (ArcGIS Pro), which is version 3.5. The reason is that it contains a module (arcpy) which is only present with this installation.

I am aware that laspy works with Python 2.7, but as pointed I tried to install the fork of GeospatialPython. Nevertheless, I failed to have it working though. What I did was:

- downloaded the zip from the forked repository and unzipped it to a directory (let's call it [DIR])

- opened a cmd terminal with admin privileges (I'm on Win10) and cd to the root laspy directory (as explained in the docs)

- did "python setup.py build"

I am sure I am using the right interpreter (the 3.5 shipped with ArcGIS Pro). After that, I received:

```
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import laspy
  File "C:\Umberto\lidar\laspy\geospatial_fork\laspy-master\laspy\__init__.py", line 3, in <module>
    import base
ImportError: No module named 'base'
```

Does anyone have any idea on what's going on? Is it because the laspy in the fork I am using is just compatible with python 3.4 and not 3.5? Or am I missing something else? Thanks in advance!

**Comment by hobu** [comment]
>  Is it because the laspy in the fork I am using is just compatible with python 3.4 and not 3.5?

Yep.

There is effort ongoing for Python 3 compatibility https://github.com/laspy/laspy/pull/45 but it is not complete. I don't think it would be so much more effort to push it across the line, but I don't know the details of what exactly is left to do.

**Comment by umbe1987** [comment]
@hobu Thanks for the response. This explains my errors. Anyway, really looking forward to see any improvement in the python 3 compatibility. I'd like to help, but I saw there are issues in the tests and unfortunately I don't even know how to perform "a test"... Again, thanks. Really appreciate the effort in this valuable package!

**Comment by umbe1987** [comment]
Just tried to install the GeospatialPython fork against a Python34 install. Still receiving the same error when building:
```
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import laspy
  File "C:\umberto\laspy\geospatial_fork\laspy-master\laspy\__init__.py", line 3
, in <module>
    import base
ImportError: No module named 'base'
```
I'm on a Windows 7 machine, and I am trying to build via a cmd shell with admin privilege by:
```
cd [LASPY-PATH]
python setup.py build
```

**Comment by umbe1987** [comment]
Also, if I add 'laspy' to pythonpath, I can import laspy, but not all other submodules of it (e.g. import laspy works, but from laspy import file doesn't (No module named 'file'))

**Comment by umbe1987** [comment]
I ended up using the 'python3' branch from the 'davidcaron' fork ([this one](https://github.com/davidcaron/laspy/tree/python3)) and it actually installed correctly against my python 35 installation. Also, I tested my code and it worked. It might be buggy but I will use (test) this version until an official release compatible with python 3 will come out. Thanks for this very useful tool!
